-- Inserir projectos por BU (ignora duplicados)

-- BIO
INSERT INTO projectos (nome, bu_id) VALUES
  ('VOC', (SELECT id FROM bus WHERE nome = 'BIO')),
  ('VOC EVOLUTION', (SELECT id FROM bus WHERE nome = 'BIO')),
  ('COM & EXPERIÊNCIA - ETOLL', (SELECT id FROM bus WHERE nome = 'BIO')),
  ('SOM & FEEDBACK - ETOLL', (SELECT id FROM bus WHERE nome = 'BIO')),
  ('SINALÉTICA TICKET MANUAL', (SELECT id FROM bus WHERE nome = 'BIO'))
ON CONFLICT DO NOTHING;

-- BRISA
INSERT INTO projectos (nome, bu_id) VALUES
  ('ALINHAMENTO MARKETING MENSAL', (SELECT id FROM bus WHERE nome = 'BRISA')),
  ('DMK | QUALTRICS', (SELECT id FROM bus WHERE nome = 'BRISA')),
  ('FRONTIFY | DMK', (SELECT id FROM bus WHERE nome = 'BRISA')),
  ('BALANCEAMENTO CARGAS | SUSTENTABILIDADE BAE', (SELECT id FROM bus WHERE nome = 'BRISA')),
  ('PROJETOS CÁTIA DMK', (SELECT id FROM bus WHERE nome = 'BRISA'))
ON CONFLICT DO NOTHING;

-- UCB
INSERT INTO projectos (nome, bu_id) VALUES
  ('EQUIPA UX | CX', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('SHAREPOINT UX', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('CLIENT JOURNEYS', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('AMPLIFY', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('LOJAS & CC', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('AUSÊNCIA | FÉRIAS', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('AUSÊNCIA | FORMAÇÃO', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('AUSÊNCIA | DOENÇA', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('LOJA OEIRAS', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('DESIGN SYSTEM | EQUIPA UX', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('QUALTRICS PLATFORM', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('VOC RFI | RFP', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('VOC | GERAL', (SELECT id FROM bus WHERE nome = 'UCB')),
  ('PERSONALIZAÇÃO CONTACT CENTER UCB', (SELECT id FROM bus WHERE nome = 'UCB'))
ON CONFLICT DO NOTHING;

-- CONTROLAUTO
INSERT INTO projectos (nome, bu_id) VALUES
  ('VOC', (SELECT id FROM bus WHERE nome = 'CONTROLAUTO')),
  ('VOC EVOLUTION', (SELECT id FROM bus WHERE nome = 'CONTROLAUTO'))
ON CONFLICT DO NOTHING;

-- CONTROLAUTO_ITV
INSERT INTO projectos (nome, bu_id) VALUES
  ('VOC', (SELECT id FROM bus WHERE nome = 'CONTROLAUTO_ITV')),
  ('VOC EVOLUTION', (SELECT id FROM bus WHERE nome = 'CONTROLAUTO_ITV'))
ON CONFLICT DO NOTHING;

-- COLIBRI
INSERT INTO projectos (nome, bu_id) VALUES
  ('VOC', (SELECT id FROM bus WHERE nome = 'COLIBRI')),
  ('VOC EVOLUTION', (SELECT id FROM bus WHERE nome = 'COLIBRI')),
  ('DMK - CLIENTE COLIBRI 2026', (SELECT id FROM bus WHERE nome = 'COLIBRI')),
  ('BASE DADOS COLIBRI', (SELECT id FROM bus WHERE nome = 'COLIBRI')),
  ('LP CAMPANHA COLIBRI', (SELECT id FROM bus WHERE nome = 'COLIBRI'))
ON CONFLICT DO NOTHING;

-- VVTE
INSERT INTO projectos (nome, bu_id) VALUES
  ('VOC', (SELECT id FROM bus WHERE nome = 'VVTE')),
  ('VOC EVOLUTION', (SELECT id FROM bus WHERE nome = 'VVTE')),
  ('FLUXOS TPA', (SELECT id FROM bus WHERE nome = 'VVTE')),
  ('WEBSITE', (SELECT id FROM bus WHERE nome = 'VVTE')),
  ('CARREGADORES CAMPUS', (SELECT id FROM bus WHERE nome = 'VVTE')),
  ('HUB OEIRAS', (SELECT id FROM bus WHERE nome = 'VVTE'))
ON CONFLICT DO NOTHING;

-- VIA_VERDE
INSERT INTO projectos (nome, bu_id) VALUES
  ('VVPT-19670 | BIRD | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-18210 | PLANNER | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-21082 | TÁXIS | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-21108 | GEMINI | VIA VERDE INOVAÇÃO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-24795 | SENTIANCE | VIA VERDE INOVAÇÃO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-22255 | B2B (2025) | VIA VERDE B2B', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('WEBSITE PÚBLICO | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('ACESSIBILIDADE | VIA VERDE INOVAÇÃO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-24252 EV CHARGING | VV to CPO PLATFORM', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-24604 B2B | CAR MOBILITY PLANS', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-26010 PARKING | CARPLAY & ANDROID AUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VOC | VIA VERDE', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VOC EVOLUTION | VIA VERDE', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('FINAL MILE | VIA VERDE OPERAÇÕES', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('EXTRATOS | VIA VERDE OPERAÇÕES', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('MOVE IZI | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('PILOTO FROTA B2B | VIA VERDE B2B', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('ALINHAMENTO PRODUTO | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VV CIDADE | VIA VERDE PRODUTO', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-26092 | SEARCH FOR A LOCATION | ADDRESS PRESENTATION', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-22656 | SEARCH FOR A LOCATION', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VVPT-18424 | APP | CREATE AND REMOVE ACCOUNTS', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('PERSONAL MOBILITY | BIRD (REFINAMENTOS)', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('PARKING RESERVATIONS', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('DISCRIMINAÇÕES POSITIVAS - A2 e A6', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('REGISTER/DISABLE ONLINE THE VIA VERDE ACCOUNT VIA APP', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('MULTIFACTOR AUTHENTICATION - BIOMETRIC AUTH', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('WEBSITE | MULTIFACTOR AUTHENT 2.0', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VALIDAÇÃO PAR NIF-IBAN + REVERSÃO REGRA INIBIÇÃO DD', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('CONTROL | DIGITAL SERVICE REAL TIME METHODS (CC)', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('COST REDUCTION | DD MASSIFICATION (B2C)', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VOC NEDLINQ', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('VOC EVOLUTION NEDLINQ', (SELECT id FROM bus WHERE nome = 'VIA_VERDE')),
  ('WEBSITE PÚBLICO NEDLINQ', (SELECT id FROM bus WHERE nome = 'VIA_VERDE'))
ON CONFLICT DO NOTHING;
